// generator.js — Bash/PowerShell script generation and zip download

const Generator = (() => {

  // ── Helpers ───────────────────────────────────────────────────────

  function escapeForBashHeredoc(str) {
    // Single-quoted heredoc delimiter prevents all expansion, so no escaping needed
    // But we need to make sure the EOF delimiter doesn't appear in content
    return str;
  }

  function escapeForPowerShellHereString(str) {
    // PowerShell single-quoted here-strings (@'...'@) prevent all expansion
    // The only thing that can break it is '@ at the start of a line
    return str.replace(/^'@/gm, " '@");
  }

  // ── Build CLAUDE.md content ───────────────────────────────────────

  function buildClaudeMdContent(selectedSections) {
    if (selectedSections.length === 0) return null;

    let content = "# Global Claude Code Instructions\n";
    for (const section of selectedSections) {
      content += "\n" + section.content + "\n";
    }
    return content;
  }

  // ── Build settings.json content ───────────────────────────────────

  function buildSettingsJson(selectedSettings) {
    if (selectedSettings.length === 0) return null;

    const result = {
      permissions: {
        allow: [],
        deny: []
      }
    };

    for (const setting of selectedSettings) {
      if (setting.id === "permissions-deny") {
        result.permissions.deny = setting.content;
      } else if (setting.id === "settings-bypass") {
        result.permissions.defaultMode = setting.content.value;
      } else if (setting.id === "settings-precompact-hook") {
        result.hooks = { PreCompact: setting.content.value };
      } else if (setting.id === "settings-thinking") {
        result[setting.content.key] = setting.content.value;
      } else if (Array.isArray(setting.content)) {
        result.permissions.allow.push(...setting.content);
      }
    }

    // Clean up empty arrays
    if (result.permissions.allow.length === 0) delete result.permissions.allow;
    if (result.permissions.deny.length === 0) delete result.permissions.deny;
    if (Object.keys(result.permissions).length === 0) delete result.permissions;

    return Object.keys(result).length > 0 ? JSON.stringify(result, null, 2) : null;
  }

  // ── Build command file contents ───────────────────────────────────

  function getCommandContent(cmd) {
    // Return the full original content for the command file
    return cmd.content;
  }

  // ── Bash script generator ─────────────────────────────────────────

  function generateBash(state) {
    const sections = CONFIG_DATA.claudeMd.filter(s => state.claudeMd[s.id]);
    const settings = CONFIG_DATA.settings.filter(s => state.settings[s.id]);
    const commands = CONFIG_DATA.commands.filter(c => state.commands[c.id]);

    if (state._reset) {
      return `#!/usr/bin/env bash
# Claude Code Config Reset
# Generated by boilerplate.md
# Removes custom config and restores Claude Code defaults.
set -euo pipefail

CLAUDE_DIR="\${HOME}/.claude"

echo "Resetting Claude Code to defaults..."
echo ""

# Remove custom config files
[ -f "\${CLAUDE_DIR}/CLAUDE.md" ] && rm "\${CLAUDE_DIR}/CLAUDE.md" && echo "  Removed CLAUDE.md"
[ -f "\${CLAUDE_DIR}/settings.json" ] && rm "\${CLAUDE_DIR}/settings.json" && echo "  Removed settings.json"

# Remove custom commands
if [ -d "\${CLAUDE_DIR}/commands" ]; then
  rm -r "\${CLAUDE_DIR}/commands"
  echo "  Removed commands/"
fi

echo ""
echo "Done! Claude Code has been reset to defaults."
echo "Restart Claude Code to pick up the changes."`;
    }

    if (sections.length === 0 && settings.length === 0 && commands.length === 0) {
      return "# Nothing selected. Pick some components above.";
    }

    let script = `#!/usr/bin/env bash
# Claude Code Config Installer
# Generated by boilerplate.md
# Source: https://github.com/ds1/claude-code-config
set -euo pipefail

CLAUDE_DIR="\${HOME}/.claude"
COMMANDS_DIR="\${CLAUDE_DIR}/commands"

echo "Installing Claude Code configuration..."
echo ""

# Create directories
mkdir -p "\${CLAUDE_DIR}"
`;

    if (commands.length > 0) {
      script += `mkdir -p "\${COMMANDS_DIR}"\n`;
    }

    script += "\n";

    // CLAUDE.md
    const claudeMdContent = buildClaudeMdContent(sections);
    if (claudeMdContent) {
      script += `# ── CLAUDE.md ──────────────────────────────────────────────────────
cat << 'CLAUDE_MD_EOF' > "\${CLAUDE_DIR}/CLAUDE.md"
${claudeMdContent}
CLAUDE_MD_EOF
echo "  Created CLAUDE.md (${sections.length} sections)"
`;
    }

    // settings.json
    const settingsContent = buildSettingsJson(settings);
    if (settingsContent) {
      script += `
# ── settings.json ─────────────────────────────────────────────────
cat << 'SETTINGS_EOF' > "\${CLAUDE_DIR}/settings.json"
${settingsContent}
SETTINGS_EOF
echo "  Created settings.json (${settings.length} groups)"
`;
    }

    // Commands
    if (commands.length > 0) {
      script += `\n# ── Slash commands ─────────────────────────────────────────────────\n`;
      for (const cmd of commands) {
        const content = getCommandContent(cmd);
        script += `cat << 'CMD_${cmd.filename.replace(/[^a-zA-Z0-9]/g, "_").toUpperCase()}_EOF' > "\${COMMANDS_DIR}/${cmd.filename}"
${content}
CMD_${cmd.filename.replace(/[^a-zA-Z0-9]/g, "_").toUpperCase()}_EOF
`;
      }
      script += `echo "  Created ${commands.length} slash commands"\n`;
    }

    script += `
echo ""
echo "Done! Configuration installed to \${CLAUDE_DIR}"
echo "Restart Claude Code to pick up the changes."
`;

    return script;
  }

  // ── PowerShell script generator ───────────────────────────────────

  function generatePowerShell(state) {
    const sections = CONFIG_DATA.claudeMd.filter(s => state.claudeMd[s.id]);
    const settings = CONFIG_DATA.settings.filter(s => state.settings[s.id]);
    const commands = CONFIG_DATA.commands.filter(c => state.commands[c.id]);

    if (state._reset) {
      return `# Claude Code Config Reset
# Generated by boilerplate.md
# Removes custom config and restores Claude Code defaults.
$ErrorActionPreference = "Stop"

$ClaudeDir = Join-Path $env:USERPROFILE ".claude"

Write-Host "Resetting Claude Code to defaults..."
Write-Host ""

# Remove custom config files
$claudeMdPath = Join-Path $ClaudeDir "CLAUDE.md"
if (Test-Path $claudeMdPath) { Remove-Item $claudeMdPath; Write-Host "  Removed CLAUDE.md" }

$settingsPath = Join-Path $ClaudeDir "settings.json"
if (Test-Path $settingsPath) { Remove-Item $settingsPath; Write-Host "  Removed settings.json" }

# Remove custom commands
$commandsPath = Join-Path $ClaudeDir "commands"
if (Test-Path $commandsPath) { Remove-Item $commandsPath -Recurse; Write-Host "  Removed commands/" }

Write-Host ""
Write-Host "Done! Claude Code has been reset to defaults."
Write-Host "Restart Claude Code to pick up the changes."`;
    }

    if (sections.length === 0 && settings.length === 0 && commands.length === 0) {
      return "# Nothing selected. Pick some components above.";
    }

    let script = `# Claude Code Config Installer
# Generated by boilerplate.md
# Source: https://github.com/ds1/claude-code-config
$ErrorActionPreference = "Stop"

$ClaudeDir = Join-Path $env:USERPROFILE ".claude"
$CommandsDir = Join-Path $ClaudeDir "commands"

Write-Host "Installing Claude Code configuration..."
Write-Host ""

# Create directories
New-Item -ItemType Directory -Force -Path $ClaudeDir | Out-Null
`;

    if (commands.length > 0) {
      script += `New-Item -ItemType Directory -Force -Path $CommandsDir | Out-Null\n`;
    }

    script += "\n";

    // CLAUDE.md
    const claudeMdContent = buildClaudeMdContent(sections);
    if (claudeMdContent) {
      const escaped = escapeForPowerShellHereString(claudeMdContent);
      script += `# -- CLAUDE.md --
$claudeMd = @'
${escaped}
'@
Set-Content -Path (Join-Path $ClaudeDir "CLAUDE.md") -Value $claudeMd -Encoding UTF8
Write-Host "  Created CLAUDE.md (${sections.length} sections)"
`;
    }

    // settings.json
    const settingsContent = buildSettingsJson(settings);
    if (settingsContent) {
      const escaped = escapeForPowerShellHereString(settingsContent);
      script += `
# -- settings.json --
$settingsJson = @'
${escaped}
'@
Set-Content -Path (Join-Path $ClaudeDir "settings.json") -Value $settingsJson -Encoding UTF8
Write-Host "  Created settings.json (${settings.length} groups)"
`;
    }

    // Commands
    if (commands.length > 0) {
      script += `\n# -- Slash commands --\n`;
      for (const cmd of commands) {
        const content = getCommandContent(cmd);
        const escaped = escapeForPowerShellHereString(content);
        const varName = `$cmd_${cmd.filename.replace(/[^a-zA-Z0-9]/g, "_")}`;
        script += `${varName} = @'
${escaped}
'@
Set-Content -Path (Join-Path $CommandsDir "${cmd.filename}") -Value ${varName} -Encoding UTF8
`;
      }
      script += `Write-Host "  Created ${commands.length} slash commands"\n`;
    }

    script += `
Write-Host ""
Write-Host "Done! Configuration installed to $ClaudeDir"
Write-Host "Restart Claude Code to pick up the changes."
`;

    return script;
  }

  // ── Zip generator ─────────────────────────────────────────────────

  async function generateZip(state) {
    const sections = CONFIG_DATA.claudeMd.filter(s => state.claudeMd[s.id]);
    const settings = CONFIG_DATA.settings.filter(s => state.settings[s.id]);
    const commands = CONFIG_DATA.commands.filter(c => state.commands[c.id]);

    const zip = new JSZip();
    const claudeDir = zip.folder(".claude");

    // CLAUDE.md
    const claudeMdContent = buildClaudeMdContent(sections);
    if (claudeMdContent) {
      claudeDir.file("CLAUDE.md", claudeMdContent);
    }

    // settings.json
    const settingsContent = buildSettingsJson(settings);
    if (settingsContent) {
      claudeDir.file("settings.json", settingsContent);
    }

    // Commands
    if (commands.length > 0) {
      const commandsDir = claudeDir.folder("commands");
      for (const cmd of commands) {
        commandsDir.file(cmd.filename, getCommandContent(cmd));
      }
    }

    const blob = await zip.generateAsync({ type: "blob" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "claude-code-config.zip";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  // ── Copy to clipboard ─────────────────────────────────────────────

  async function copyToClipboard(text, btn) {
    try {
      await navigator.clipboard.writeText(text);
      btn.classList.add("copied");
      const label = btn.querySelector(".copy-label");
      const orig = label.textContent;
      label.textContent = "Copied!";
      setTimeout(() => {
        btn.classList.remove("copied");
        label.textContent = orig;
      }, 2000);
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement("textarea");
      textarea.value = text;
      textarea.style.position = "fixed";
      textarea.style.opacity = "0";
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      btn.classList.add("copied");
      const label = btn.querySelector(".copy-label");
      const orig = label.textContent;
      label.textContent = "Copied!";
      setTimeout(() => {
        btn.classList.remove("copied");
        label.textContent = orig;
      }, 2000);
    }
  }

  return {
    generateBash,
    generatePowerShell,
    generateZip,
    copyToClipboard,
    buildClaudeMdContent,
    buildSettingsJson
  };
})();
